## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - 1.1
os:
  - linux

codecov: true
coveralls: true

notifications:
  email: false

jobs:
  include:
    - stage: "Test"
      script:
        - julia -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: julia test/coverage.jl
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
